sudo: true
language: go
services:
  - docker
matrix:
  include:
  - go: 1.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- go test $(go list ./... | grep -v vendor)
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      make container
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io;
      docker push quay.io/k8scsi/csi-provisioner:canary;
    fi
